version: '3.7'

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    depends_on:
        - php
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - .:/var/www
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
  adminer:
    image: adminer
    restart: always
    ports:
        - 8081:8080
